/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;


import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author d13
 */
public class interfaz extends javax.swing.JFrame {
    private TableColumnModel tableColumnModel;

    private JRadioButton[] patron_rb;   //rb=RadioButton
    private String[] patron_strg;       //strg=String
    private String patron_row = "";     //row=Patron de la tabla

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
        /**
         * Centra Form
         */
        this.setLocationRelativeTo(null);
        /**
         * Configura tamaño de Columnas
         */
        this.setConfigurationColums();
        this.getRadioButtons();
        this.createPatronString();
        
    }
    
    private void setConfigurationColums()
    {
        tableColumnModel = Table_Leer.getColumnModel();
        tableColumnModel.getColumn(0).setPreferredWidth(100);
        tableColumnModel.getColumn(1).setPreferredWidth(100);
        tableColumnModel.getColumn(2).setPreferredWidth(700);
    }
    
    private void getRadioButtons()
    {
        JRadioButton[] patron = 
        {
            this.F0_C0, this.F0_C1, this.F0_C2, this.F0_C3, this.F0_C4, this.F0_C5, this.F0_C6,
            this.F1_C0, this.F1_C1, this.F1_C2, this.F1_C3, this.F1_C4, this.F1_C5, this.F0_C6,
            this.F2_C0, this.F2_C1, this.F2_C2, this.F2_C3, this.F2_C4, this.F2_C5, this.F0_C6,
            this.F3_C0, this.F3_C1, this.F3_C2, this.F3_C3, this.F3_C4, this.F3_C5, this.F0_C6,
            this.F4_C0, this.F4_C1, this.F4_C2, this.F4_C3, this.F4_C4, this.F4_C5, this.F0_C6,
            this.F5_C0, this.F5_C1, this.F5_C2, this.F5_C3, this.F5_C4, this.F5_C5, this.F0_C6,
            this.F6_C0, this.F6_C1, this.F6_C2, this.F6_C3, this.F6_C4, this.F6_C5, this.F0_C6,
        };
        this.patron_rb = patron;
    }
    
    private void createPatronString()
    {
        patron_strg = new String[patron_rb.length];
    }
    
    private void getPatron()
    {
        for (int i = 0; i < patron_rb.length; i++) {
            if (patron_rb[i].isSelected())
            {
                patron_strg[i] = "+1";
            }
            else{
                patron_strg[i] = "-1";
            }
            patron_row +=patron_strg[i];
        }
    }
    
    private void showPatron()
    {
        String row = "";
        int p = 0;
        for (int i = 0; i < patron_strg.length; i++) {
            row += patron_strg[i];
            if (p==6) {
                p=0;
                System.out.println(row);
                row = "";
            }
            else{
                p++;
            }
            
        }
    }
    private void addPatronTable()
    {
        DefaultTableModel defaultTableModel = (DefaultTableModel) Table_Leer.getModel();
        defaultTableModel.addRow(new Object[]{"id","Descripcion",patron_row});
        //LIMPIA PATRON
        patron_row = "";
    }
    
    private void clearPatron()
    {
        for (int i = 0; i < patron_rb.length; i++) {
            if (patron_rb[i].isSelected()) {
                patron_rb[i].setSelected(false);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TPT = new javax.swing.JTabbedPane();
        P_Leer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Leer = new javax.swing.JTable();
        P_Escribir = new javax.swing.JPanel();
        P_Container_Patron = new javax.swing.JPanel();
        F0_C0 = new javax.swing.JRadioButton();
        F0_C1 = new javax.swing.JRadioButton();
        F0_C2 = new javax.swing.JRadioButton();
        F0_C3 = new javax.swing.JRadioButton();
        F0_C4 = new javax.swing.JRadioButton();
        F0_C5 = new javax.swing.JRadioButton();
        F1_C0 = new javax.swing.JRadioButton();
        F1_C1 = new javax.swing.JRadioButton();
        F1_C2 = new javax.swing.JRadioButton();
        F1_C3 = new javax.swing.JRadioButton();
        F1_C4 = new javax.swing.JRadioButton();
        F1_C5 = new javax.swing.JRadioButton();
        F2_C0 = new javax.swing.JRadioButton();
        F2_C1 = new javax.swing.JRadioButton();
        F2_C2 = new javax.swing.JRadioButton();
        F2_C3 = new javax.swing.JRadioButton();
        F2_C4 = new javax.swing.JRadioButton();
        F2_C5 = new javax.swing.JRadioButton();
        F3_C4 = new javax.swing.JRadioButton();
        F3_C0 = new javax.swing.JRadioButton();
        F3_C1 = new javax.swing.JRadioButton();
        F3_C2 = new javax.swing.JRadioButton();
        F3_C3 = new javax.swing.JRadioButton();
        F3_C5 = new javax.swing.JRadioButton();
        F4_C0 = new javax.swing.JRadioButton();
        F4_C1 = new javax.swing.JRadioButton();
        F4_C2 = new javax.swing.JRadioButton();
        F4_C3 = new javax.swing.JRadioButton();
        F4_C4 = new javax.swing.JRadioButton();
        F4_C5 = new javax.swing.JRadioButton();
        F5_C0 = new javax.swing.JRadioButton();
        F5_C1 = new javax.swing.JRadioButton();
        F5_C2 = new javax.swing.JRadioButton();
        F5_C3 = new javax.swing.JRadioButton();
        F5_C4 = new javax.swing.JRadioButton();
        F5_C5 = new javax.swing.JRadioButton();
        F6_C0 = new javax.swing.JRadioButton();
        F6_C1 = new javax.swing.JRadioButton();
        F6_C2 = new javax.swing.JRadioButton();
        F6_C3 = new javax.swing.JRadioButton();
        F6_C4 = new javax.swing.JRadioButton();
        F6_C5 = new javax.swing.JRadioButton();
        F0_C6 = new javax.swing.JRadioButton();
        F1_C6 = new javax.swing.JRadioButton();
        F2_C6 = new javax.swing.JRadioButton();
        F3_C6 = new javax.swing.JRadioButton();
        F4_C6 = new javax.swing.JRadioButton();
        F5_C6 = new javax.swing.JRadioButton();
        F6_C6 = new javax.swing.JRadioButton();
        P_Container_Acciones_Leer = new javax.swing.JPanel();
        Btn_ReadPatron = new javax.swing.JButton();
        Btn_LimpiarPatron = new javax.swing.JButton();
        P_Container_Acciones_Desc = new javax.swing.JPanel();
        TxF_Descripcion = new javax.swing.JTextField();
        P_Acerca = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Table_Leer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Descripcion", "Patron"
            }
        ));
        jScrollPane1.setViewportView(Table_Leer);

        javax.swing.GroupLayout P_LeerLayout = new javax.swing.GroupLayout(P_Leer);
        P_Leer.setLayout(P_LeerLayout);
        P_LeerLayout.setHorizontalGroup(
            P_LeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
        );
        P_LeerLayout.setVerticalGroup(
            P_LeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_LeerLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        TPT.addTab("Leer", P_Leer);

        P_Container_Patron.setBorder(javax.swing.BorderFactory.createTitledBorder("Patron"));
        P_Container_Patron.setToolTipText("");
        P_Container_Patron.setName(""); // NOI18N

        F0_C0.setToolTipText("0,0");

        F0_C1.setToolTipText("0,1");

        F0_C2.setToolTipText("0,2");

        F0_C3.setToolTipText("0,3");

        F0_C4.setToolTipText("0,4");

        F0_C5.setToolTipText("0,5");

        F1_C0.setToolTipText("1,0");

        F1_C1.setToolTipText("1,1");

        F1_C2.setToolTipText("1,2");

        F1_C3.setToolTipText("1,3");

        F1_C4.setToolTipText("1,4");

        F1_C5.setToolTipText("1,5");

        F2_C0.setToolTipText("2,0");

        F2_C1.setToolTipText("2,1");

        F2_C2.setToolTipText("2,2");

        F2_C3.setToolTipText("2,3");

        F2_C4.setToolTipText("2,4");

        F2_C5.setToolTipText("2,5");

        F3_C4.setToolTipText("3,4");

        F3_C0.setToolTipText("3,0");

        F3_C1.setToolTipText("3,1");

        F3_C2.setToolTipText("3,2");

        F3_C3.setToolTipText("3,3");

        F3_C5.setToolTipText("3,5");

        F4_C0.setToolTipText("4,0");

        F4_C1.setToolTipText("4,1");

        F4_C2.setToolTipText("4,2");

        F4_C3.setToolTipText("4,3");

        F4_C4.setToolTipText("4,4");

        F4_C5.setToolTipText("4,5");

        F5_C0.setToolTipText("5,0");

        F5_C1.setToolTipText("5,1");

        F5_C2.setToolTipText("5,2");

        F5_C3.setToolTipText("5,3");

        F5_C4.setToolTipText("5,4");

        F5_C5.setToolTipText("5,5");

        F6_C0.setToolTipText("6,0");

        F6_C1.setToolTipText("6,1");

        F6_C2.setToolTipText("6,2");

        F6_C3.setToolTipText("6,3");

        F6_C4.setToolTipText("6,4");

        F6_C5.setToolTipText("6,5");

        F0_C6.setToolTipText("0,5");

        F1_C6.setToolTipText("1,5");

        F2_C6.setToolTipText("2,5");

        F3_C6.setToolTipText("3,5");

        F4_C6.setToolTipText("4,5");

        F5_C6.setToolTipText("5,5");

        F6_C6.setToolTipText("6,5");

        javax.swing.GroupLayout P_Container_PatronLayout = new javax.swing.GroupLayout(P_Container_Patron);
        P_Container_Patron.setLayout(P_Container_PatronLayout);
        P_Container_PatronLayout.setHorizontalGroup(
            P_Container_PatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_Container_PatronLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_Container_PatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_Container_PatronLayout.createSequentialGroup()
                        .addComponent(F0_C0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F0_C1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F0_C2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F0_C3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F0_C4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F0_C5))
                    .addGroup(P_Container_PatronLayout.createSequentialGroup()
                        .addComponent(F1_C0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F1_C1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F1_C2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F1_C3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F1_C4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F1_C5))
                    .addGroup(P_Container_PatronLayout.createSequentialGroup()
                        .addComponent(F2_C0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F2_C1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F2_C2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F2_C3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F2_C4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F2_C5))
                    .addGroup(P_Container_PatronLayout.createSequentialGroup()
                        .addComponent(F3_C0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F3_C1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F3_C2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F3_C3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F3_C4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F3_C5))
                    .addGroup(P_Container_PatronLayout.createSequentialGroup()
                        .addComponent(F4_C0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F4_C1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F4_C2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F4_C3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F4_C4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F4_C5))
                    .addGroup(P_Container_PatronLayout.createSequentialGroup()
                        .addComponent(F5_C0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F5_C1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F5_C2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F5_C3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F5_C4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F5_C5))
                    .addGroup(P_Container_PatronLayout.createSequentialGroup()
                        .addComponent(F6_C0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F6_C1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F6_C2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F6_C3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F6_C4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F6_C5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P_Container_PatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(F0_C6)
                    .addComponent(F1_C6)
                    .addComponent(F2_C6)
                    .addComponent(F3_C6)
                    .addComponent(F4_C6)
                    .addComponent(F5_C6)
                    .addComponent(F6_C6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        P_Container_PatronLayout.setVerticalGroup(
            P_Container_PatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_Container_PatronLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_Container_PatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_Container_PatronLayout.createSequentialGroup()
                        .addComponent(F0_C6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F1_C6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F2_C6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F3_C6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F4_C6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F5_C6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F6_C6))
                    .addGroup(P_Container_PatronLayout.createSequentialGroup()
                        .addGroup(P_Container_PatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(F0_C2)
                            .addComponent(F0_C3)
                            .addGroup(P_Container_PatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(F0_C0)
                                .addComponent(F0_C1)
                                .addComponent(F0_C4))
                            .addComponent(F0_C5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(P_Container_PatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(F1_C2)
                            .addGroup(P_Container_PatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(F1_C0)
                                .addComponent(F1_C1)
                                .addComponent(F1_C3)
                                .addComponent(F1_C4))
                            .addComponent(F1_C5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(P_Container_PatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(F2_C2)
                            .addGroup(P_Container_PatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(F2_C0)
                                .addComponent(F2_C1)
                                .addComponent(F2_C3)
                                .addComponent(F2_C4))
                            .addComponent(F2_C5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(P_Container_PatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(F3_C2)
                            .addGroup(P_Container_PatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(F3_C0)
                                .addComponent(F3_C1)
                                .addComponent(F3_C3)
                                .addComponent(F3_C4))
                            .addComponent(F3_C5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(P_Container_PatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(F4_C2)
                            .addGroup(P_Container_PatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(F4_C0)
                                .addComponent(F4_C1)
                                .addComponent(F4_C3)
                                .addComponent(F4_C4))
                            .addComponent(F4_C5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(P_Container_PatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(F5_C2)
                            .addGroup(P_Container_PatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(F5_C0)
                                .addComponent(F5_C1)
                                .addComponent(F5_C3)
                                .addComponent(F5_C4))
                            .addComponent(F5_C5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(P_Container_PatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(F6_C2)
                            .addGroup(P_Container_PatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(F6_C0)
                                .addComponent(F6_C1)
                                .addComponent(F6_C3)
                                .addComponent(F6_C4))
                            .addComponent(F6_C5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        P_Container_Acciones_Leer.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));

        Btn_ReadPatron.setText("Leer Patron");
        Btn_ReadPatron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ReadPatronActionPerformed(evt);
            }
        });

        Btn_LimpiarPatron.setText("Limpiar Patron");
        Btn_LimpiarPatron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LimpiarPatronActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P_Container_Acciones_LeerLayout = new javax.swing.GroupLayout(P_Container_Acciones_Leer);
        P_Container_Acciones_Leer.setLayout(P_Container_Acciones_LeerLayout);
        P_Container_Acciones_LeerLayout.setHorizontalGroup(
            P_Container_Acciones_LeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_Container_Acciones_LeerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_Container_Acciones_LeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Btn_ReadPatron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_LimpiarPatron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        P_Container_Acciones_LeerLayout.setVerticalGroup(
            P_Container_Acciones_LeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_Container_Acciones_LeerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_ReadPatron)
                .addGap(18, 18, 18)
                .addComponent(Btn_LimpiarPatron)
                .addContainerGap())
        );

        P_Container_Acciones_Desc.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripcion"));

        TxF_Descripcion.setToolTipText("Letra que representa el Patron");

        javax.swing.GroupLayout P_Container_Acciones_DescLayout = new javax.swing.GroupLayout(P_Container_Acciones_Desc);
        P_Container_Acciones_Desc.setLayout(P_Container_Acciones_DescLayout);
        P_Container_Acciones_DescLayout.setHorizontalGroup(
            P_Container_Acciones_DescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_Container_Acciones_DescLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TxF_Descripcion)
                .addContainerGap())
        );
        P_Container_Acciones_DescLayout.setVerticalGroup(
            P_Container_Acciones_DescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxF_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout P_EscribirLayout = new javax.swing.GroupLayout(P_Escribir);
        P_Escribir.setLayout(P_EscribirLayout);
        P_EscribirLayout.setHorizontalGroup(
            P_EscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_EscribirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(P_Container_Patron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(P_EscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(P_Container_Acciones_Desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(P_Container_Acciones_Leer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(431, Short.MAX_VALUE))
        );
        P_EscribirLayout.setVerticalGroup(
            P_EscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_EscribirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_EscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(P_EscribirLayout.createSequentialGroup()
                        .addComponent(P_Container_Acciones_Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(P_Container_Acciones_Leer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(P_Container_Patron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        TPT.addTab("Escribir", P_Escribir);

        javax.swing.GroupLayout P_AcercaLayout = new javax.swing.GroupLayout(P_Acerca);
        P_Acerca.setLayout(P_AcercaLayout);
        P_AcercaLayout.setHorizontalGroup(
            P_AcercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 797, Short.MAX_VALUE)
        );
        P_AcercaLayout.setVerticalGroup(
            P_AcercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        TPT.addTab("tab3", P_Acerca);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 797, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        TPT.addTab("tab4", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 797, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        TPT.addTab("tab5", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 797, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        TPT.addTab("tab6", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TPT)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TPT)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ReadPatronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ReadPatronActionPerformed
        if (!TxF_Descripcion.getText().isEmpty())
        {
            this.getPatron();
            this.showPatron();
            this.addPatronTable();
            JOptionPane.showMessageDialog(rootPane, "Patron Agragdo", "Confirmacion", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Falta Agregar una descripcion", "Alerta", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_Btn_ReadPatronActionPerformed

    private void Btn_LimpiarPatronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimpiarPatronActionPerformed
        this.clearPatron();
    }//GEN-LAST:event_Btn_LimpiarPatronActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_LimpiarPatron;
    private javax.swing.JButton Btn_ReadPatron;
    private javax.swing.JRadioButton F0_C0;
    private javax.swing.JRadioButton F0_C1;
    private javax.swing.JRadioButton F0_C2;
    private javax.swing.JRadioButton F0_C3;
    private javax.swing.JRadioButton F0_C4;
    private javax.swing.JRadioButton F0_C5;
    private javax.swing.JRadioButton F0_C6;
    private javax.swing.JRadioButton F1_C0;
    private javax.swing.JRadioButton F1_C1;
    private javax.swing.JRadioButton F1_C2;
    private javax.swing.JRadioButton F1_C3;
    private javax.swing.JRadioButton F1_C4;
    private javax.swing.JRadioButton F1_C5;
    private javax.swing.JRadioButton F1_C6;
    private javax.swing.JRadioButton F2_C0;
    private javax.swing.JRadioButton F2_C1;
    private javax.swing.JRadioButton F2_C2;
    private javax.swing.JRadioButton F2_C3;
    private javax.swing.JRadioButton F2_C4;
    private javax.swing.JRadioButton F2_C5;
    private javax.swing.JRadioButton F2_C6;
    private javax.swing.JRadioButton F3_C0;
    private javax.swing.JRadioButton F3_C1;
    private javax.swing.JRadioButton F3_C2;
    private javax.swing.JRadioButton F3_C3;
    private javax.swing.JRadioButton F3_C4;
    private javax.swing.JRadioButton F3_C5;
    private javax.swing.JRadioButton F3_C6;
    private javax.swing.JRadioButton F4_C0;
    private javax.swing.JRadioButton F4_C1;
    private javax.swing.JRadioButton F4_C2;
    private javax.swing.JRadioButton F4_C3;
    private javax.swing.JRadioButton F4_C4;
    private javax.swing.JRadioButton F4_C5;
    private javax.swing.JRadioButton F4_C6;
    private javax.swing.JRadioButton F5_C0;
    private javax.swing.JRadioButton F5_C1;
    private javax.swing.JRadioButton F5_C2;
    private javax.swing.JRadioButton F5_C3;
    private javax.swing.JRadioButton F5_C4;
    private javax.swing.JRadioButton F5_C5;
    private javax.swing.JRadioButton F5_C6;
    private javax.swing.JRadioButton F6_C0;
    private javax.swing.JRadioButton F6_C1;
    private javax.swing.JRadioButton F6_C2;
    private javax.swing.JRadioButton F6_C3;
    private javax.swing.JRadioButton F6_C4;
    private javax.swing.JRadioButton F6_C5;
    private javax.swing.JRadioButton F6_C6;
    private javax.swing.JPanel P_Acerca;
    private javax.swing.JPanel P_Container_Acciones_Desc;
    private javax.swing.JPanel P_Container_Acciones_Leer;
    private javax.swing.JPanel P_Container_Patron;
    private javax.swing.JPanel P_Escribir;
    private javax.swing.JPanel P_Leer;
    private javax.swing.JTabbedPane TPT;
    private javax.swing.JTable Table_Leer;
    private javax.swing.JTextField TxF_Descripcion;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    

}
